[project]
name = "tissue-classification"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hydra-core>=1.3.2",
    "mlflow>=3.6.0",
    "omegaconf>=2.3.0",
    "ray>=2.51.1",
    "rationai-mlkit>=0.2.2",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "ruff>=0.14.5",
]

[tool.uv.sources]
rationai-mlkit = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/mlkit.git" }