# @package _global_

model:
  backbone:
    _target_: torch.nn.Identity

  decode_head:
    _target_: torch.nn.Linear
    in_features: ${embedding_dim}
    out_features: ${len:${class_indices}}

  class_indices: ${class_indices}

  optimizer: ???
  learning_rate: ???
  weight_decay: ???
  lbfgs: null
