# @package _global_

model: ???
output_dir: ${project_path}/embeddings
concurrency: 512
block_size: 2000
rows_per_file: 5000

tile_filters:
  tissue_stats_run_id: ${dataset.mlflow_artifacts.tissue_stats_run_id}
  tissue_stats_artifact_path: tissue_stats

metadata:
  run_name: "Embeddings: ${model}"
  description: Tile embeddings using model ${model}
  hyperparams:
    model: ${model}
    concurrency: ${concurrency}
    block_size: ${block_size}
