# @package _global_

mpp: ???
disk_factor: ???

max_concurrent: 8
mlflow_artifact_path: tissue_masks

metadata:
  run_name: Tissue Masks ${dataset.name}
  description: "Tissue masks generation (mpp ${mpp}, Disk Factor ${disk_factor})"
  hyperparams:
      mpp: ${mpp}
      disk_factor: ${disk_factor}