# @package _global_

defaults:
  - /data: dataset
  - _self_

metadata:
  run_name: create_dataset_map
  description: Initial generation of WSI-Annotation map with metadata.

output_csv_name: "dataset_map.csv"
output_json_name: "class_map.json"